### ISSUE TITLE
Question, why not to upgrade to Python 3?

### ISSUE THREAD

**Issue by nengxu** [noamraph/dreampie#2]
Thanks for bringing us the best Python shell. I'm primarily using Ruby now for work. However, Python remains one of my favorite languages. 

Although Python 3 has been live for a few years, it seems that Python community still has the inertia to stick with Python 2. For example, one cool boy called Ansible, and another called Fabric.

May I ask in the case of Dreampie, why not to upgrade to Python 3? Thanks.

**Comment by BrenBarn** [comment]
It is really no longer the case that Python 3 is not widely available.  I am keeping Python 2 around largely because of DreamPie.  It would be great to have a version of DreamPie that would run on Python 3, but I fear this is not an easy task because of its PyGTK dependencies.
