### ISSUE TITLE
Unable to run release version

### ISSUE THREAD

**Issue by IgorGanapolsky** [noamraph/dreampie#71]
Hello,
when I try to run DreamPie on my Mac (OS Sierra), I get this error:
> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/dreampie", line 3, in <module>
    from dreampielib.gui import main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dreampielib/gui/__init__.py", line 240
    except StartError, e:
                     ^
SyntaxError: invalid syntax

Please advise,
Igor

**Comment by BrenBarn** [comment]
Unfortunately, DreamPie doesn't work with Python 3.  You can run Python 3 inside DreamPie, but you still need Python 2 to run DreamPie itself.

**Comment by IgorGanapolsky** [comment]
How can I specify which Python version to launch DreamPie with?

**Comment by BrenBarn** [comment]
There is a simple example right at the bottom of the front page: https://github.com/noamraph/dreampie

**Comment by IgorGanapolsky** [comment]
@BrenBarn I tried that, and here is what happens:
**igorganapolsky:~$ dreampie python2.7**
>Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/dreampie", line 3, in <module>
    from dreampielib.gui import main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dreampielib/gui/__init__.py", line 240
    except StartError, e:
                     ^
SyntaxError: invalid syntax

**Comment by BrenBarn** [comment]
That specifies which version to run *inside* DreamPie.  You still need to *install* Python 2.7 and use that to run DreamPie itself, with something like `python2.7 dreampie.py`.  Do you have Python 2.7 installed?

**Comment by IgorGanapolsky** [comment]
I do have it installed.  I can either run python2 or python3.  The default command is python3, though.

**Comment by BrenBarn** [comment]
Then try running `python2 dreampie.py`.  If you get errors about libraries not found, you need to install those libraries for Python 2.

**Comment by IgorGanapolsky** [comment]
That works, thanks!
